In [1]:
import numpy as np


In [3]:
heights = [165,170,171,180,189,178]

print(type(heights))

heights_np = np.array(heights)
print(heights_np)
print(type(heights_np))

<class 'list'>
[165 170 171 180 189 178]
<class 'numpy.ndarray'>


In [26]:
weights = np.array([[50,60,70,55],[88,56,89,33]])
print(weights.dtype)
print('weights',weights)

weights
#all numpy array datatype must be same

int64
weights [[50 60 70 55]
 [88 56 89 33]]


array([[50, 60, 70, 55],
       [88, 56, 89, 33]])

In [22]:
 #attribute of np array

 # .reshape() to change the matrix structure of array


 fruits = np.array([['apple','pear','berry'],['guava','melon','lemon']])

print(fruits)

print(fruits.dtype)
print(fruits.shape)
print(fruits.size)
print(fruits.strides)  #varies in machines

new_fruits = np.reshape(fruits,(3,2))   # or fruits.reshape(3.2)
print(new_fruits)

[['apple' 'pear' 'berry']
 ['guava' 'melon' 'lemon']]
<U5
(2, 3)
6
(60, 20)
[['apple' 'pear']
 ['berry' 'guava']
 ['melon' 'lemon']]
